"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from t742874298_1 import utils
from t742874298_1.types import BaseModel


class APIErrorInvalidInputData(BaseModel):
    status: int

    error: str


class APIErrorInvalidInput(Exception):
    r"""Not Found error"""

    data: APIErrorInvalidInputData

    def __init__(self, data: APIErrorInvalidInputData):
        self.data = data

    def __str__(self) -> str:
        return utils.marshal_json(self.data, APIErrorInvalidInputData)
