"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
import pydantic
from t742874298_1.types import BaseModel
from t742874298_1.utils import FieldMetadata, PathParamMetadata
from typing_extensions import Annotated, TypedDict


class GetPetByIDRequestTypedDict(TypedDict):
    pet_id: int
    r"""ID of pet to return"""


class GetPetByIDRequest(BaseModel):
    pet_id: Annotated[
        int,
        pydantic.Field(alias="petId"),
        FieldMetadata(path=PathParamMetadata(style="simple", explode=False)),
    ]
    r"""ID of pet to return"""
